# INPUT A NUMBER
# CHECK DIVISIBLE BY 5 AND 7
# IF YES THEN PRINT ITS DIVISIBLE BY 5 AND 7
# CHECK THE GIVEN NUMBER DIVISIBLE BY 5 ONLY, 7 ONLY
# THEN THE NUMBER NOT DIVISIBLE BY 5 AND 7

n=int(input('Enter the number :'))
if n%5==0 and n%7==0:
    print("THE NUMBER IS DIVISIBLE BY 5 AND 7")
elif n%5==0:
    print("THE NUMBER IS DIVISIBLE BY 5")
elif n%7==0:
    print("THE NUMBER IS DIVISIBLE BY 7")
else:
    print("THE NUMBER IS NOT DIVISIBLE BY BOTH 5 AND 7")